### ISSUE TITLE
"private" fails on functions with pattern matches

### ISSUE THREAD

**Issue by bryanhunter** [pragdave/private#2]
I'm really digging "private". The first issue I've hit is reproduced here...
```
  describe "Bit-syntax matching in function heads" do
    defmodule MatchingFun do
      use Private 

      private chunk(<<"ABC", therest::binary>>) do
        therest
      end
    end

    test "bitsyntax pattern matches work" do
      assert MatchingFun.chunk(<<"ABCDEF">>) == "DEF"
    end
  end
```
yields
```
warning: variable "therest" does not exist and is being expanded to "therest()", please use parentheses to remove the ambiguity or change the variable name
  test/private_test.exs:63

** (CompileError) test/private_test.exs:63: undefined function therest/0
    (private) expanding macro: Private.private/2
    test/private_test.exs:62: PrivateTest.MatchingFun (module)
    (elixir) lib/code.ex:370: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:57: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5
```

At first, I thought the bug might be specific to bit-syntax in the function head, but it turns out simpler destructuring (as pattern matching tuples below) also causes trouble...
```
    defmodule MatchingFun do
      use Private 
      private reverse_tuple({first, second}) do
        {second, first}
      end
    end
```
yields 
```
** (CompileError) test/private_test.exs:77: undefined function second/0
    (private) expanding macro: Private.private/2
    test/private_test.exs:76: PrivateTest.MatchingFun (module)
    (elixir) lib/code.ex:370: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:57: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5
```

**Comment by pragdave** [comment]
That's not quite how you use `private`. The following seems to work for me:

~~~ elixir
defmodule TTest do
  use ExUnit.Case
  # doctest T
  describe "Bit-syntax matching in function heads" do
    defmodule MatchingFun do
      use Private 

      private do
        def chunk(<<"ABC", therest::binary>>) do
          therest
        end
      end
    end

    test "bitsyntax pattern matches work" do
      assert MatchingFun.chunk(<<"ABCDEF">>) == "DEF"
    end
  end
end
~~~

**Comment by bryanhunter** [comment]
Haha! Wow... from my "try it out" project last week to adding it to a new project today, I completely blanked on the wrapping block. Thanks, and apologies for the noise. 😊
